# Generated by Django 2.2.5 on 2019-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarinfo',
            name='link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitarinfo',
            name='price',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
