# Generated by Django 2.2.5 on 2019-09-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20190909_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarinfo',
            name='brand_choice',
            field=models.CharField(choices=[('FENDER', 'fender'), ('GIBSON', 'gibson'), ('GRETSCH', 'gretsch'), ('SUHR', 'suhr'), ('IBANEZ', 'ibanez'), ('PRS', 'prs'), ('UNKNOWN', 'unknown')], default='FND', max_length=10),
        ),
    ]
