# Generated by Django 2.2.5 on 2019-09-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20190911_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarinfo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
