# Generated by Django 2.2.5 on 2019-09-12 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20190911_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitarinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
