# Generated by Django 2.2.5 on 2019-09-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_guitarinfo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarinfo',
            name='brand_choice',
            field=models.CharField(choices=[('FENDER', 'fender'), ('GIBSON', 'gibson'), ('GRETSCH', 'gretsch'), ('SUHR', 'suhr'), ('IBANEZ', 'ibanez'), ('PRS', 'prs'), ('UNKNOWN', 'unknown'), ('STRANDBERG', 'strandberg'), ('EVH', 'EVH'), ('PAUL REED SMITH', 'prs')], default='FND', max_length=20),
        ),
    ]
