# Generated by Django 2.2.5 on 2019-09-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20190913_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarinfo',
            name='brand_choice',
            field=models.CharField(choices=[('FENDER', 'fender'), ('GIBSON', 'gibson'), ('GRETSCH', 'gretsch'), ('SUHR', 'suhr'), ('IBANEZ', 'ibanez'), ('PRS', 'prs'), ('UNKNOWN', 'unknown'), ('STRANDBERG', 'strandberg'), ('EVH', 'EVH'), ('(PRS)', 'prs')], default='FND', max_length=10),
        ),
    ]
