# Generated by Django 2.2.5 on 2019-09-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20190916_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarinfo',
            name='img_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
