# Generated by Django 2.2.5 on 2019-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_auto_20190916_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarinfo',
            name='brand_choice',
            field=models.CharField(choices=[('FENDER', 'fender'), ('GIBSON', 'gibson'), ('GRETSCH', 'gretsch'), ('SUHR', 'suhr'), ('IBANEZ', 'ibanez'), ('PRS', 'prs'), ('UNKNOWN', 'unknown'), ('STRANDBERG', 'strandberg'), ('EVH', 'EVH'), ('SMITH', 'Paul Reed Smith'), ('SCHECTER', 'schecter'), ('TAYLOR', 'taylor'), ('ANDERSON', 'tom anderson'), ('MAYONES', 'mayones'), ('MUSIC', 'music man')], default='FND', max_length=10),
        ),
    ]
