# Generated by Django 2.2.5 on 2019-09-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0026_auto_20190922_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarinfo',
            name='brand_choice',
            field=models.CharField(choices=[('FENDER', 'fender'), ('GIBSON', 'gibson'), ('GRETSCH', 'gretsch'), ('SUHR', 'suhr'), ('IBANEZ', 'ibanez'), ('PRS', 'prs'), ('UNKNOWN', 'unknown'), ('STRANDBERG', 'strandberg'), ('EVH', 'EVH'), ('SCHECTER', 'schecter'), ('TAYLOR', 'taylor'), ('TOM', 'tom anderson'), ('MAYONES', 'mayones'), ('MUSIC', 'music man'), ('CHARVEL', 'Charvel'), ('JACKSON', 'Jackson'), ('TOKAI', 'Tokai')], default='FND', max_length=10),
        ),
    ]
